In [19]:
A = np.array([[-1, 1],
              [1, 1]])
B = np.array([0, 1]).T

In [20]:
np.linalg.inv(A).dot(B)

array([1/2, 1/2])

## $\vec{v} = (A^TA)^{-1}A^T\vec{x}$

In [35]:
import numpy as np
A = np.array([[1, 0],
              [1/3, 2/3],
              [2/3, 1/3]]
              )
b = np.array([3, 2, 2]).T

x = np.linalg.inv(A.T.dot(A)).dot(A.T).dot(b)

In [36]:
import fractions
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})
print(x)

[17/6 4/3]


In [1]:
y = lambda x: x^2 -2*x+1

In [4]:
v = np.array([y(-2), y(-1), y(0), y(1), y(2), y(3), y(4)])
v1 = np.array([1, 1, 1, 1, 1])
v2 = np.array([1, 1, 1, -1, 1])
v3 = np.array([1, -1, 1, -1, 1])

In [5]:
p = np.array([60, 40, 50, 40])
x = np.array([.5, -1, .5, -2])

In [7]:
print(np.correlate(p, x, 'full')) # k =0  -> corr = -3

[-120 -50 -140 -65 -10 -15 20]


In [8]:
plt.scatter(range(-2, 3, 1), np.correlate(np.array([0, -1, 2]), np.array([-2, 3, 0]), 'full'))

NameError: name 'plt' is not defined

In [1]:
25/4 - 5 * 7/2 + 49/4

1.0

In [6]:
4 + 25 + 36+4

69

In [10]:
x1 = np.array([2, 0, -1, 1])
x2 = np.array([1, -1, 1, -1])
x3 = np.array([2, -2, -8, 7])
x4 = np.array([4, 1, -2, 2])

In [11]:
print(np.dot(x1, x2))

0


In [12]:
print(np.dot(x1, x3))
print(np.dot(x1, x4))

19
12


In [29]:
A = np.array([[0.5, 0, 0],
              [0.5, 0, 0],
              [0, 0, 0]])
B = np.array([1, 0, 0]).T

In [34]:
A.dot(A).dot(B)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [86]:
A = np.array([[0.5, 0.5, 0],
              [0.5, 0.5, 0],
              [0, 0, 1]])
B = np.array([[1, 0, 0],
              [0, 0.5, 0.5],
              [0, 0.5, 0.5]])

In [87]:
C = np.array([1, 0, 0]).T

In [88]:
X = B.dot(A)

In [95]:
X = np.array([[1, 1],
              [0.5, 0.5]])

In [96]:
K = X
for i in range(100):
    K = K.dot(X)

In [97]:
C = np.array([0.5, 0.5]).T

In [98]:
K.dot(C)

array([406561177535215232, 203280588767607616])

In [85]:
X.dot(C)

array([1/2, 1/4, 1/4])

In [69]:
X.dot(X).dot(C)

array([3/8, 3/8, 1/4])