In [1]:
from sympy import Symbol, solve

R1 = Symbol('R1')
R2 = Symbol('R2')
Vs = Symbol('Vs')
Is = Symbol('Is')
IR1 = Symbol('IR1')
IR2 = Symbol('IR2')
u2 = Symbol('u2')
u1 = Symbol('u1')

In [3]:
import numpy as np
A = np.array([[0, 1, -1, 0, 0],
              [1, 1, 0, 0, 0],
              [0, 0, 0, 1, 0],
              [0, R1, 0, -1, 1],
              [0, 0, R2, 0, -1]])
x = np.array([Is, IR1, IR2, u1, u2]).T
solv = np.array([0, 0, Vs, 0, 0]).T

In [15]:
A = np.array([[1, 1, 0, 0, 0],
              [0, -1, 1, 1, 0],
              [0, 0, 0, -1, 1],
              [-1, 0, -1, 0, -1],
              [0, 4, 4, 0, 0],
              [0, 4, 0, 2, 2],
              [0, 0, 4, -2, -2]])
B = np.array([0,0,0,0,5,5,0])

In [25]:
sol = np.linalg.lstsq(A, B.T)[0]
print(sol)

[-0.83333333  0.83333333  0.41666667  0.41666667  0.41666667]


/var/folders/m5/b577jf4d20jc309f4phr3lvr0000gn/T/ipykernel_11014/2197888790.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  sol = np.linalg.lstsq(A, B.T)[0]


In [26]:
import fractions
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})
print(sol)

[-5/6 5/6 5/12 5/12 5/12]


In [1]:
import numpy as np
A = np.array([[1, -1, -1, 0],
              [1, 0, 0, 0],
              [0, 1, 0, 1],
              [0, 0, 1, -1]])
B = np.array([0, 10/1.8, -10/1.8, 0])

In [2]:
sol = np.linalg.lstsq(A, B.T)[0]
print(sol)

[ 2.77777778 -0.92592593  0.92592593 -1.85185185]


/var/folders/m5/b577jf4d20jc309f4phr3lvr0000gn/T/ipykernel_2641/2197888790.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  sol = np.linalg.lstsq(A, B.T)[0]


In [3]:
import fractions
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})
print(sol)

[25/9 -25/27 25/27 -50/27]


In [16]:
np.linalg.solve(A, B.T)

LinAlgError: Last 2 dimensions of the array must be square

In [9]:
A.shape

(6, 5)

In [28]:
A = np.array([[1, 1, 0],
             [0, 0, 1],
             [0, 5, -1]])
B = np.array([0, 5, 0])

sol = np.linalg.lstsq(A, B.T)[0]
print(sol)

[-1 1 5]


/var/folders/m5/b577jf4d20jc309f4phr3lvr0000gn/T/ipykernel_11014/1025942009.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  sol = np.linalg.lstsq(A, B.T)[0]
